### ISSUE TITLE
Explore watchexec + (Paketo) Buildpacks

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/rapid-feedback-loops#3]
As a first step toward integrating the `watchexec` buildpack with our language families, we should learn more about `watchexec` itself. Some questions that immediately come to mind are:

- What is the default behaviour?

- What is syntax is relevant for what we are trying to accomplish?

- What limitations exist/what caveats are relevant to our work?

- How does `watchexec` do process management? (i.e. What signals are sent? How are child processes killed?)

Acceptance Criteria
A document should be created in this repository which contains the findings of the investigation as well as any unresolved questions for stakeholders.

**Comment by fg-j** [comment]
Findings have been summarized in: https://github.com/paketo-buildpacks/rapid-feedback-loops/blob/14824c9de399288e4a0a232b8029fc57895f17aa/watchexec-experiments/README.md
